### ISSUE TITLE
Response.js errors on launch

### ISSUE THREAD

**Issue by rob-226** [jgkaplan/gemini-server#7]
Any idea why I would get the error below? Using your example files. Node version is 12.14.1

Thanks

```
robs-imac:gemcap rob$ node index.js 
/Users/rob/Projects/gemcap/Response.js:13
    #setMeta(m){
            ^

SyntaxError: Unexpected token '('
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/rob/Projects/gemcap/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
robs-imac:gemcap rob$ 
```

**Comment by jgkaplan** [comment]
I'm not sure. I'm currently using Node 14 and don't have an issue. I'll look into it.

**Comment by jgkaplan** [comment]
I'm guessing it's my use of the # symbol in the method name. I can remove that. Also, to run the example, use `node example.js` rather than `node index.js`
